### PR TITLE
Update to nunit3 and netstandard 2.0

### PR DESCRIPTION
**Pull request by mtnrbq**
Fresh clone from source compiles and fully tests on VS2017 15.5.
~~You will need the NUnit3 test adapter VSIX installed~~
*Nunit3TestAdapter is included in the Tests group in paket.references*

Gjallarhorn now targets netstandard2.0
NUnit upgraded to v3 (#27 ignored to try to reduce footprint of change)
Gjallarhorn.Linq.Tests (csproj) - .net Framework 4.6.1
Gjallarhorn.Tests (fsproj) - .net framework 4.6.1 - had to edit .fsproj to reference Gjallarhorn as VS2017 gui tooling reports error.

#43

### CODE REVIEW

**Comment by TeaDrivenDev** [comment]
There is a NuGet package for the NUnit VisualStudio adapter (https://www.nuget.org/packages/NUnit3TestAdapter/) - wouldn't it be better to include that instead of requiring the VSIX? That generally seems to be the preferred way now (xUnit dropped their VSIX altogether and only offer the NuGet package now).

**Comment by mtnrbq** [comment]
Fair point - update to nunit3 was purely for the .net standard test support and keeping the tests 'as they were' so hadn't considered changing approach to VS/test framework integration

**Comment by mtnrbq** [comment]
I've just re-reviewed the paket.dependencies, and the paket.references for the Test group, and Nunit3TestAdapter is included, so the VSIX is **not** needed - I'll update the original comment

**Comment by mtnrbq** [comment]
@ReedCopsey  - I've completed the work for upgrading Gjallarhorn.Bindable (ReedCopsey/Gjallarhorn.Bindable#13) based on a local build of this change. What are your thoughts on the following? (I'm not super familiar with GIT, so may be on the wrong track)
* Merge this change onto a new branch
* build to nuget as beta
* update the Gjallarhorn.Bindable to reference the nuget beta
* validate operation
* merge to master
* build to new release version on nuget
* update the Gjallarhorn.Bindable to reference the release nuget

**Comment by mtnrbq** [comment]
@ReedCopsey  - let me know if there is more i can do to this to make it ready

**Comment by bigjonroberts** [comment]
@ReedCopsey Should we just update the current Gjallarhorn.Bindable package to have top version range in the packet.dependencies?

**Comment by bigjonroberts** [comment]
I think that Build.fsx may need some a tweak or two.  I tried to run a build right after cloning and had to run the `dotnet restore` command before the `build.cmd` to get it to run (I'm using dotent `2.1.2`.

**Comment by bigjonroberts** [comment]
Also had a failing test:
```
1) Failed : Gjallarhorn.Linq.Tests.SignalLinq.SelectAsyncTracksProperly
  Expected: False
  But was:  True
   at Gjallarhorn.Linq.Tests.SignalLinq.<SelectAsyncTracksProperly>d__11.MoveNext() in C:\work\elicio\Gjallarhorn\tests\Gjallarhorn.Linq.Tests\SignalLinq.cs:line 181
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context)
```
I may have some time to delve further later this weekend.  But thought I would report these issues here before this gets merged.

**Comment by mtnrbq** [comment]
Hi Jon,
Did you get the failed test in VS or through command line? (I'm getting all 124 passing in VS)

**Comment by bigjonroberts** [comment]
@mtnrbq I ran it through the command line.
If I build and run it in VS, all the tests pass.  After building once in VS, the tests continue to pass from the command line.  However, try for yourself, cloning a clean repo on this branch and run ./build.cmd - you will have the same issues.
I'm opening a PR against your branch to add a `DotNetCLI.Restore` to the build script to work around the first issue and to increment the version in the README.md, but if you can't build from command-line, I think that's a problem.
I used beyond-compare to look at a diff of the output from VS build against FAKE build, and couldn't tell what was different.  I updated to latest dotnet SDK - 2.1.4, that also made no difference.  I tried to compare the MSBuild detailed build logs between the VS build and the FAKE build as well - couldn't make heads nor tails of what is different.

**Comment by bigjonroberts** [comment]
I think this is the underlying issue.  Looks like we just need to invoke the tests from the command-line using a different method:
https://github.com/nunit/dotnet-test-nunit/issues/108

**Comment by bigjonroberts** [comment]
One of the commenters on that issue mentioned that it might be worthwhile to migrate to xunit if you are targeting .netstandard and building on .netcore.  xunit is actually used by the core dotnet team, too.  I think that xunit structure works better with FSharp syntax in general.

If there is interest in seeing it, I would be willing to do it.

This would be separate just from getting this test runner working correctly on the command line.

**Comment by mtnrbq** [comment]
@bigjonroberts - with the pr you made to specifically invoke restore, I'm getting a command line build and test execute on a clean copy of the repo with no errors - are you able to retest?. 
There is an issue #27  to move all tests to Expecto, so I'm guessing that is the desired approach @ReedCopsey

**Comment by FoggyFinder** [comment]
> There is an issue #27 to move all tests to Expecto, so I'm guessing that is the desired approach 

@mtnrbq  Yeah and I have rewrite most part of tests already (really it was more than 6 month ago but for some reason I stopped for a while).

So, maybe it make sense to shift work related #27 to the separate branch/PR? 

If so I can find these files and send the PR to your fork. But it will not early than Tuesday or Wednesday next week.

But there is one thing that bothering me - perhaps Expecto can [increase](https://github.com/mathnet/mathnet-symbolics/issues/50) time to compile tests project. So maybe better strategy would be to use Expecto for [Gjallarhorn.Bindable](https://github.com/ReedCopsey/Gjallarhorn.Bindable) before moving the core project ? (Just to make sure Expecto will good choice not only in theory)

**Comment by mtnrbq** [comment]
@FoggyFinder @bigjonroberts @ReedCopsey  - if there is no longer a problem with a build including tests from the command line, straight after a clean get from the repo (to be confirmed) - can this PR be merged?
Then the changes to testing can be done separately / cleanly.

**Comment by ReedCopsey** [comment]
@FoggyFinder Not too worried about the increase in build time - from what I've seen, its typically minor, and even then, worth it.

**Comment by bigjonroberts** [comment]
If it builds on the automated build system that’s all I was worried about. 

I upgraded to latest Vs2017 a few days ago and will see if that makes any difference in my environment.

**Comment by ReedCopsey** [comment]
@bigjonroberts Will require a recent update of VS 2017 to build now. Netstandard 2 wasn't supported until recently in VS.

**Comment by bigjonroberts** [comment]
Yes I know. Upgrade was from 15.5 to 15.6. Doubt it changed the dotnet runtime or SDK. But I’ll give it a try.

**Pull request merged**
