### PR TITLE
Make Func's explict about the generic type they accept. 

### PR DESCRIPTION
**Pull request by willsam100**
This is to fix a bug on mobile that threw an Invalid IL exception.

Is master the best branch for this to be merged into? 

I have tested this on the simulator for iOS.I have not yet tested this on Android (will confirm this soon).
Testing still to be done:
- test on latest version of mono for iOS and Android released by Xamarin
- test on latest version of FSharp (4.1)
- test this doesn't break anything related to WPF and windows

There are no unit (or other) tests on here. I could add a UI test (Android only since windows users won't be able to run iOS) if that is desired to prevent this bug from popping up again.

### CODE REVIEW

**Comment by ReedCopsey** [comment]
@willsam100 Master is fine - let me know once you've done some basic testing, and I'm happy to merge this.  From what I can see, it appears like it'd be fine (mostly just removing some inference), but a check would be nice.

I'm happy to merge once you confirm it works and doesn't break android/wpf.

**Comment by ReedCopsey** [comment]
@willsam100 Any progress on this? Just wanted confirmation on it before we merge...

**Comment by willsam100** [comment]
I am unable to get access to a windows machine with the right version of visual studio installed (since 2017 is broken). Also, I tried building this locally on my Mac with Visual Studio using Mono 5.2.X and I'm getting build errors (not sure if they are related to this PR or not). I will close this PR, fix the up the errors, and re-open at a later stage if the changes are still required.

**Comment by ReedCopsey** [comment]
Thanks! Why is 2017 broken for you?

**Comment by willsam100** [comment]
I did have access to a windows machine earlier this year, but 2017 VS on windows (to my understanding) broke many things  in F#, and I couldn't get anything running. From what I have read, the latest update 17.3 has fixed some of this, but it still isn't perfect. I only use a Mac, so fixing this problems was less than trivial for me, and I no longer have access to a windows machine now. I believe that VS 2015 on windows still works fine with F#, which is probably what I should have installed earlier in the year.

**Pull request closed without merging**
